// ──────────────────────────────────────────────────
// Problem  : 1914. Cyclically Rotating a Grid
// Difficulty: Medium
// Tags     : Array, Matrix, Simulation
// Link     : https://leetcode.com/problems/cyclically-rotating-a-grid/
// Runtime  : 5 ms (beats 82%)
// Memory   : 47200000 (beats 85%)
// Language : java
// Copyright: (c) 2026 sharan8760. All rights reserved.
// Synced by: leetie
// ──────────────────────────────────────────────────

import java.util.ArrayList;
import java.util.List;

class Solution {
    public int[][] rotateGrid(int[][] grid, int k) {
            int m = grid.length;
                    int n = grid[0].length;
                            
                                    // Number of layers is half of the minimum dimension
                                            int numLayers = Math.min(m, n) / 2;
                                                    
                                                            for (int layer = 0; layer < numLayers; layer++) {
                                                                        // Define the boundaries of the current layer
                                                                                    int top = layer;
                                                                                                int bottom = m - 1 - layer;
                                                                                                            int left = layer;
                                                                                                                        int right = n - 1 - layer;
                                                                                                                                    
                                                                                                                                                // Step 1: Extract the elements of the current layer in counter-clockwise order
                                                                                                                                                            List<Integer> elements = new ArrayList<>();
                                                                                                                                                                        
                                                                                                                                                                                    // Top row (left to right)
                                                                                                                                                                                                for (int j = left; j <= right; j++) elements.add(grid[top][j]);
                                                                                                                                                                                                            // Right column (top + 1 to bottom)
                                                                                                                                                                                                                        for (int i = top + 1; i <= bottom; i++) elements.add(grid[i][right]);
                                                                                                                                                                                                                                    // Bottom row (right - 1 to left)
                                                                                                                                                                                                                                                for (int j = right - 1; j >= left; j--) elements.add(grid[bottom][j]);
                                                                                                                                                                                                                                                            // Left column (bottom - 1 to top + 1)
                                                                                                                                                                                                                                                                        for (int i = bottom - 1; i > top; i--) elements.add(grid[i][left]);
                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                // Step 2: Calculate the effective number of rotations
                                                                                                                                                                                                                                                                                                            int len = elements.size();
                                                                                                                                                                                                                                                                                                                        int shift = k % len; 
                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                // Step 3: Put the elements back into the grid starting from the shifted index
                                                                                                                                                                                                                                                                                                                                                            int idx = shift;
                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                    // Top row
                                                                                                                                                                                                                                                                                                                                                                                                for (int j = left; j <= right; j++) {
                                                                                                                                                                                                                                                                                                                                                                                                                grid[top][j] = elements.get(idx % len);
                                                                                                                                                                                                                                                                                                                                                                                                                                idx++;
                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Right column
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    for (int i = top + 1; i <= bottom; i++) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    grid[i][right] = elements.get(idx % len);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    idx++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Bottom row
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        for (int j = right - 1; j >= left; j--) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        grid[bottom][j] = elements.get(idx % len);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        idx++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Left column
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for (int i = bottom - 1; i > top; i--) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            grid[i][left] = elements.get(idx % len);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            idx++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return grid;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }