// ──────────────────────────────────────────────────
// Problem  : 3629. Minimum Jumps to Reach End via Prime Teleportation
// Difficulty: Medium
// Tags     : Array, Hash Table, Math, Breadth-First Search, Number Theory
// Link     : https://leetcode.com/problems/minimum-jumps-to-reach-end-via-prime-teleportation/
// Runtime  : 159 ms (beats 77%)
// Memory   : 264256000 (beats 19%)
// Language : java
// Copyright: (c) 2026 sharan8760. All rights reserved.
// Synced by: leetie
// ──────────────────────────────────────────────────

import java.util.*;

class Solution {
    // 1. Precompute Sieve statically so it only runs ONCE for all testcases
        static final int MAX = 1000005;
            static final int[] spf = new int[MAX];
                
                    static {
                            for (int i = 2; i < MAX; i++) {
                                        spf[i] = i;
                                                }
                                                        for (int i = 2; i * i < MAX; i++) {
                                                                    if (spf[i] == i) {
                                                                                    for (int j = i * i; j < MAX; j += i) {
                                                                                                        if (spf[j] == j) {
                                                                                                                                spf[j] = i;
                                                                                                                                                    }
                                                                                                                                                                    }
                                                                                                                                                                                }
                                                                                                                                                                                        }
                                                                                                                                                                                            }
                                                                                                                                                                                                
                                                                                                                                                                                                    public int minJumps(int[] nums) {
                                                                                                                                                                                                            int n = nums.length;
                                                                                                                                                                                                                    if (n <= 1) return 0;
                                                                                                                                                                                                                            
                                                                                                                                                                                                                                    // 2. Build buckets for each prime mapping to indices divisible by that prime
                                                                                                                                                                                                                                            List<Integer>[] buckets = new ArrayList[MAX];
                                                                                                                                                                                                                                                    for (int i = 0; i < n; i++) {
                                                                                                                                                                                                                                                                int val = nums[i];
                                                                                                                                                                                                                                                                            while (val > 1) {
                                                                                                                                                                                                                                                                                            int p = spf[val];
                                                                                                                                                                                                                                                                                                            if (buckets[p] == null) {
                                                                                                                                                                                                                                                                                                                                buckets[p] = new ArrayList<>();
                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                buckets[p].add(i);
                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                // Remove all occurrences of the prime factor p
                                                                                                                                                                                                                                                                                                                                                                                                                while (val % p == 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                    val /= p;
                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // 3. Breadth-First Search (BFS)
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                int[] dist = new int[n];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Arrays.fill(dist, -1);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                dist[0] = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Use ArrayDeque instead of LinkedList for faster queue operations
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        Queue<Integer> q = new ArrayDeque<>();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                q.offer(0);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                while (!q.isEmpty()) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            int u = q.poll();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // 1. Adjacent Steps
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (u + 1 < n && dist[u + 1] == -1) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                dist[u + 1] = dist[u] + 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (u + 1 == n - 1) return dist[u + 1]; // Early exit check
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                q.offer(u + 1);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (u - 1 >= 0 && dist[u - 1] == -1) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        dist[u - 1] = dist[u] + 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        q.offer(u - 1);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // 2. Prime Teleportation
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Check if nums[u] itself is a prime number
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (nums[u] > 1 && spf[nums[u]] == nums[u]) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    int p = nums[u];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (buckets[p] != null) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        for (int v : buckets[p]) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (dist[v] == -1) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            dist[v] = dist[u] + 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (v == n - 1) return dist[v]; // Early exit check
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    q.offer(v);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Clear the bucket to prevent revisiting and inner-loop TLE
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        buckets[p] = null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            return -1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }