// ──────────────────────────────────────────────────
// Problem  : 2333. Minimum Sum of Squared Difference
// Difficulty: Medium
// Tags     : Array, Binary Search, Greedy, Sorting, Heap (Priority Queue)
// Link     : https://leetcode.com/problems/minimum-sum-of-squared-difference/
// Runtime  : 95 ms (beats 25%)
// Memory   : 125996000 (beats 9%)
// Language : java
// Copyright: (c) 2026 sharan8760. All rights reserved.
// Synced by: leetie
// ──────────────────────────────────────────────────

import java.util.*;

class Solution {
    public long minSumSquareDiff(int[] nums1, int[] nums2, int k1, int k2) {
            int n = nums1.length;
                    long totalOps = (long) k1 + (long) k2;
                            
                                    // Count frequencies of each absolute difference
                                            Map<Integer, Long> countMap = new HashMap<>();
                                                    long totalInitialDiffSq = 0;
                                                            
                                                                    for (int i = 0; i < n; i++) {
                                                                                int diff = Math.abs(nums1[i] - nums2[i]);
                                                                                            if (diff > 0) {
                                                                                                            countMap.put(diff, countMap.getOrDefault(diff, 0L) + 1L);
                                                                                                                        }
                                                                                                                                    totalInitialDiffSq += (long) diff * diff;
                                                                                                                                            }
                                                                                                                                                    
                                                                                                                                                            // Max-heap to store the differences
                                                                                                                                                                    PriorityQueue<Integer> maxHeap = new PriorityQueue<>(Collections.reverseOrder());
                                                                                                                                                                            maxHeap.addAll(countMap.keySet());
                                                                                                                                                                                    
                                                                                                                                                                                            while (totalOps > 0 && !maxHeap.isEmpty()) {
                                                                                                                                                                                                        int currDiff = maxHeap.poll();
                                                                                                                                                                                                                    long count = countMap.get(currDiff);
                                                                                                                                                                                                                                
                                                                                                                                                                                                                                            // Find the next smaller difference available
                                                                                                                                                                                                                                                        int nextDiff = maxHeap.isEmpty() ? 0 : maxHeap.peek();
                                                                                                                                                                                                                                                                    long diffDrop = currDiff - nextDiff;
                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                            // Total operations needed to reduce all elements of `currDiff` down to `nextDiff`
                                                                                                                                                                                                                                                                                                        long opsNeeded = count * diffDrop;
                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                if (totalOps >= opsNeeded) {
                                                                                                                                                                                                                                                                                                                                                // We can reduce all elements at `currDiff` down to `nextDiff`
                                                                                                                                                                                                                                                                                                                                                                totalOps -= opsNeeded;
                                                                                                                                                                                                                                                                                                                                                                                countMap.remove(currDiff);
                                                                                                                                                                                                                                                                                                                                                                                                if (nextDiff > 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                    countMap.put(nextDiff, countMap.getOrDefault(nextDiff, 0L) + count);
                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                // We don't have enough ops to bring all down, distribute evenly
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                long fullSteps = totalOps / count;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                long remainder = totalOps % count;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                int reducedDiff = currDiff - (int) fullSteps;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                int reducedDiffMinusOne = reducedDiff - 1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                countMap.put(currDiff, countMap.get(currDiff) - count);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Elements that get reduced by fullSteps
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                countMap.put(reducedDiff, countMap.getOrDefault(reducedDiff, 0L) + (count - remainder));
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (!maxHeap.contains(reducedDiff)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    maxHeap.add(reducedDiff);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    // Elements that get reduced by fullSteps + 1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (remainder > 0 && reducedDiffMinusOne >= 0) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        countMap.put(reducedDiffMinusOne, countMap.getOrDefault(reducedDiffMinusOne, 0L) + remainder);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            if (reducedDiffMinusOne > 0 && !maxHeap.contains(reducedDiffMinusOne)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    maxHeap.add(reducedDiffMinusOne);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        totalOps = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        break;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Calculate the final minimum sum of squared differences
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    long minSumSq = 0;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for (Map.Entry<Integer, Long> entry : countMap.entrySet()) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        long diff = entry.getKey();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    long count = entry.getValue();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                minSumSq += count * diff * diff;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return minSumSq;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
}