// ──────────────────────────────────────────────────
// Problem  : 1345. Jump Game IV
// Difficulty: Hard
// Tags     : Array, Hash Table, Breadth-First Search
// Link     : https://leetcode.com/problems/jump-game-iv/
// Runtime  : 61 ms (beats 72%)
// Memory   : 87040000 (beats 75%)
// Language : java
// Copyright: (c) 2026 sharan8760. All rights reserved.
// Synced by: leetie
// ──────────────────────────────────────────────────

import java.util.*;

class Solution {
    public int minJumps(int[] arr) {
            int n = arr.length;
                    if (n == 1) return 0;
                            
                                    // Map to store value -> list of indices where this value appears
                                            Map<Integer, List<Integer>> graph = new HashMap<>();
                                                    for (int i = 0; i < n; i++) {
                                                                graph.computeIfAbsent(arr[i], k -> new ArrayList<>()).add(i);
                                                                        }
                                                                                
                                                                                        Queue<Integer> queue = new LinkedList<>();
                                                                                                boolean[] visited = new boolean[n];
                                                                                                        
                                                                                                                queue.offer(0);
                                                                                                                        visited[0] = true;
                                                                                                                                int steps = 0;
                                                                                                                                        
                                                                                                                                                while (!queue.isEmpty()) {
                                                                                                                                                            int size = queue.size();
                                                                                                                                                                        
                                                                                                                                                                                    for (int i = 0; i < size; i++) {
                                                                                                                                                                                                    int curr = queue.poll();
                                                                                                                                                                                                                    
                                                                                                                                                                                                                                    // If we reach the last index, return steps
                                                                                                                                                                                                                                                    if (curr == n - 1) {
                                                                                                                                                                                                                                                                        return steps;
                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                        List<Integer> nextIndices = graph.get(arr[curr]);
                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                        // Add index curr + 1
                                                                                                                                                                                                                                                                                                                                                                        if (curr + 1 < n && !visited[curr + 1]) {
                                                                                                                                                                                                                                                                                                                                                                                            visited[curr + 1] = true;
                                                                                                                                                                                                                                                                                                                                                                                                                queue.offer(curr + 1);
                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                // Add index curr - 1
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (curr - 1 >= 0 && !visited[curr - 1]) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    visited[curr - 1] = true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        queue.offer(curr - 1);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        // Add all indices with the same value
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        if (nextIndices != null) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for (int next : nextIndices) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (!visited[next]) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                visited[next] = true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            queue.offer(next);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            // Clear the list to prevent re-visiting the same elements
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                nextIndices.clear();
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        steps++;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                return -1;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }